In [1]:
!pip install numpy

Error processing line 3 of C:\Users\ParkHanna\anaconda3\lib\site-packages\googleapis_common_protos-1.56.4-py3.10-nspkg.pth:

  Traceback (most recent call last):
    File "C:\Users\ParkHanna\anaconda3\lib\site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 562, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored


In [3]:
import numpy as np

In [4]:
data = [1,2,3]
arr = np.array(data)
print(data)
print(arr)

[1, 2, 3]
[1 2 3]


In [5]:
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
print(arr.size)

3


In [8]:
arr.dtype

dtype('int32')

In [15]:
array1 = np.arange(4)
array2 = np.zeros((4,4), dtype = float)
array3 = np.ones((5,5), dtype = int)
array4 = np.random.randint(0,10,(3,3))
array5 = np.random.normal(0,1,(3,3))
array6 = np.ones((3,3),dtype = str)

print(array1)
print(array2)
print(array3)
print(array4)
print(array5)
print(array6)

[0 1 2 3]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[4 2 1]
 [7 5 9]
 [9 4 1]]
[[ 1.42648895 -0.11399275  0.12522971]
 [ 1.82635139  0.17385824  0.33929996]
 [-0.45424437  1.45286017 -0.22919172]]
[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]


In [16]:
data = [1,2,3]
result_list = []
for i in data:
    result_list.append(i*10)
    
print(result_list)

[10, 20, 30]


In [17]:
num2 = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

print(num2[0])

[1, 2, 3]


In [19]:
num3 = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

arr = np.array(num3)

print("array num3 first element : ")
print(arr[:,0])


array num3 first element : 
[1 4 7]


In [20]:
print("array num3 first element list value in the first value : ")
print(arr[0,0])

array num3 first element list value in the first value : 
1


In [21]:
array1 = np.array([10,20,30])
array2 = np.array([50,60,70])

array3 = np.concatenate([array1, array2])

print("new shape array : ")
print(array3.shape)
print("new array element : ")
print(array3)

new shape array : 
(6,)
new array element : 
[10 20 30 50 60 70]


In [22]:
array1 = np.array([1,2,3,4])

array2 = array1.reshape((2,2))

print("original array shape :")
print(array1.shape)
print("original array element :")
print(array1)
print("new array shape :")
print(array2.shape)
print("new array element: ")
print(array2)

original array shape :
(4,)
original array element :
[1 2 3 4]
new array shape :
(2, 2)
new array element: 
[[1 2]
 [3 4]]


In [27]:
array1 = np.arange(4).reshape(1,4)

print("array1 structure and element")
print(array1.shape)
print(array1)
print("----------------------------------")

array2 = np.arange(8).reshape(2,4)

print("array2 structure and element")
print(array2.shape)
print(array2)
print("----------------------------------")
array3 = np.concatenate([array1, array2], axis=0)

print("array3 structure and element")
print(array3.shape)
print(array3)

array1 structure and element
(1, 4)
[[0 1 2 3]]
----------------------------------
array2 structure and element
(2, 4)
[[0 1 2 3]
 [4 5 6 7]]
----------------------------------
array3 structure and element
(3, 4)
[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


In [28]:
array = np.arange(8).reshape(2,4)

left, right = np.split(array,[2],axis=1)

print("original array")
print(array.shape)
print(array)
print("----------------------------------")

print("left array")
print(left.shape)
print(left)
print("----------------------------------")

print("right array")
print(right.shape)
print(right)
print("----------------------------------")

print("left array start and end element")
print(left[0][0])
print(left[1][1])
print("----------------------------------")

print("right array start and end element")
print(right[0][0])
print(right[1][1])

original array
(2, 4)
[[0 1 2 3]
 [4 5 6 7]]
----------------------------------
left array
(2, 2)
[[0 1]
 [4 5]]
----------------------------------
right array
(2, 2)
[[2 3]
 [6 7]]
----------------------------------
left array start and end element
0
5
----------------------------------
right array start and end element
2
7


In [29]:
array = np.random.randint(1,10,size=4).reshape(2,2)
print("original array")
print(array)
print("----------------------------------")

result_arr_pls = array+5

print("plus result element array")
print(result_arr_pls)
print("----------------------------------")

result_arr_mlt = array*5

print("multiplication result element array")
print(result_arr_mlt)

original array
[[5 4]
 [5 8]]
----------------------------------
plus result element array
[[10  9]
 [10 13]]
----------------------------------
multiplication result element array
[[25 20]
 [25 40]]


In [30]:
array1 = np.arange(4).reshape(2,2)
array2 = np.arange(2)

array3 = array1 + array2

print("array1 shape and element")
print(array1.shape)
print(array1)
print("----------------------------------")

print("array2 shape and element")
print(array2.shape)
print(array2)
print("----------------------------------")

print("array3 shape and element")
print(array3.shape)
print(array3)

array1 shape and element
(2, 2)
[[0 1]
 [2 3]]
----------------------------------
array2 shape and element
(2,)
[0 1]
----------------------------------
array3 shape and element
(2, 2)
[[0 2]
 [2 4]]


In [33]:
array1 = np.arange(0,8).reshape(2,4)

print("array1 shape and element")
print(array1.shape)
print(array1)
print("----------------------------------")

array2 = np.arange(0,8).reshape(2,4)

print("array2 shape and element")
print(array2.shape)
print(array2)
print("----------------------------------")

array3 = np.concatenate([array1,array2],axis = 0)

print("array3 shape and element")
print(array3.shape)
print(array3)
print("----------------------------------")

array4 = np.arange(0,4).reshape(4,1)

print("array4 shape and element")
print(array4.shape)
print(array4)
print("----------------------------------")

print("array3 plus array4 result")
print(array3 + array4)

array1 shape and element
(2, 4)
[[0 1 2 3]
 [4 5 6 7]]
----------------------------------
array2 shape and element
(2, 4)
[[0 1 2 3]
 [4 5 6 7]]
----------------------------------
array3 shape and element
(4, 4)
[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]
----------------------------------
array4 shape and element
(4, 1)
[[0]
 [1]
 [2]
 [3]]
----------------------------------
array3 plus array4 result
[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


In [34]:
array1 = np.arange(16).reshape(4,4)

print("array1 shape and element")
print(array1)
print("----------------------------------")

array2 = array1 < 8
print("array2 shape and element")
print(array2)
print("----------------------------------")

array1[array2] = 100

print("element value change array1")
print(array1)

array1 shape and element
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
----------------------------------
array2 shape and element
[[ True  True  True  True]
 [ True  True  True  True]
 [False False False False]
 [False False False False]]
----------------------------------
element value change array1
[[100 100 100 100]
 [100 100 100 100]
 [  8   9  10  11]
 [ 12  13  14  15]]


In [36]:
array = np.arange(16).reshape(4,4)

print("max : ",np.max(array))
print("min : ",np.min(array))
print("sum : ",np.sum(array))
print("avg : ",np.mean(array))

max :  15
min :  0
sum :  120
avg :  7.5


In [37]:
array = np.arange(16).reshape(4,4)
print('axis = 0 : vertical axis value sum')
print(array)
print("----------------------------------")
print('sum : ',np.sum(array, axis=0))

axis = 0 : vertical axis value sum
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
----------------------------------
sum :  [24 28 32 36]


In [40]:
array = np.array([5,3,9,10,1])
print('array element')
print(array)
print("----------------------------------")

array.sort()
print('sort array ')
print(array)
print("----------------------------------")

array.sort()
print('array desc sort')
print(array[::-1])
print("----------------------------------")

array = np.array([[5,3,9,10,1],[8,4,5,2,6]])
print('new array element')
print(array)
print("----------------------------------")

array.sort(axis=0)
print('sort array')
print(array)

array element
[ 5  3  9 10  1]
----------------------------------
sort array 
[ 1  3  5  9 10]
----------------------------------
array desc sort
[10  9  5  3  1]
----------------------------------
new array element
[[ 5  3  9 10  1]
 [ 8  4  5  2  6]]
----------------------------------
sort array
[[ 5  3  5  2  1]
 [ 8  4  9 10  6]]


In [41]:
array = np.linspace(0,10,5)
print("# equl range data made #")
print(array)
print("----------------------------------")

np.random.seed(7)
print("# reenact possible random int #")
print(np.random.randint(0,10,(2,3)))
print("----------------------------------")

print("# duplicate element delete #")
array = np.array([1,1,2,3,3,3,1,1,4])
print('original array : ', array)
print('duplicate element delete array : ',np.unique(array))
print("----------------------------------")

print("# copy array #")
array1 = np.arange(0,10)
array2 = array1.copy()

print("original array : " ,array1)
print("copy array : ", array2)

# equl range data made #
[ 0.   2.5  5.   7.5 10. ]
----------------------------------
# reenact possible random int #
[[4 9 6]
 [3 3 7]]
----------------------------------
# duplicate element delete #
original array :  [1 1 2 3 3 3 1 1 4]
duplicate element delete array :  [1 2 3 4]
----------------------------------
# copy array #
original array :  [0 1 2 3 4 5 6 7 8 9]
copy array :  [0 1 2 3 4 5 6 7 8 9]
